config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Patient CRUD
  get "patients", to: 'patients#index'

  get "patients/new", to: 'patients#new'

  post "patients", to: 'patients#create'

  get 'patients/:id', to: 'patients#show', as: "patient"

  get 'patients/:id/edit', to: 'patients#edit', as: "edit_patient"

  put 'patients/:id', to: 'patients#update'

  get 'patients/:id/delete', to: 'patients#delete', as: "delete_patient"

  # doctor CRUD

  get "doctors", to: 'doctors#index'

  get "doctors/new", to: 'doctors#new'

  post "doctors", to: 'doctors#create'

  get 'doctors/:id', to: 'doctors#show', as: "doctor"

  get 'doctors/:id/edit', to: 'doctors#edit', as: "edit_doctor"

  put 'doctors/:id', to: 'doctors#update'

  get 'doctors/:id/delete', to: 'doctors#delete', as: "delete_doctor"

  # Pres C_UD, through patients

  get "patients/:id/new_prescription", to: 'patients#new_prescription'

  post "patients/:id/:prescription_id", to: 'patients#create_prescription'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :prescriptions
  has_many :patients, through: :prescriptions

  def format
    self.name + " - " + self.specialty
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :prescriptions
  has_many :doctors, through: :prescriptions
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  def format
    "Take #{self.dose} of #{self.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = Doctor.all
  end

  def new
    @patients = Patient.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def create
    @doctor = Doctor.new
    @doctor.name = params[:doctor][:name]
    @doctor.specialty = params[:doctor][:specialty]
    @doctor.patient_ids = params[:patient_ids]
    if params[:new_patient] != ""
      @doctor.patients << Patient.create(name: params[:new_patient])
    end
    @doctor.save
    redirect_to doctor_path(@doctor.id)
  end

  def edit
    @doctor = Doctor.find(params[:id])
    @patients = Patient.all
  end

  def update
    @doctor = Doctor.find(params[:id])
    @doctor.name = params[:doctor][:name]
    @doctor.specialty = params[:doctor][:specialty]
    @doctor.patient_ids = params[:patient_ids]
    if params[:new_patient] != ""
      @doctor.patients << Patient.create(name: params[:new_patient])
    end
    @doctor.save
    redirect_to doctor_path(@doctor.id)
  end

  def delete
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to doctors_path
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.all
  end

  def new
    @doctors = Doctor.all
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def create
    @patient = Patient.new
    @patient.name = params[:patient][:name]
    @patient.doctor_ids = params[:doctor_ids]
    if params[:new_doctor] != ""
      @patient.doctors << Doctor.create(name: params[:new_doctor])
    end
    @patient.save
    redirect_to patient_path(@patient.id)
  end

  def edit
    @patient = Patient.find(params[:id])
    @doctors = Doctor.all
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.name = params[:patient][:name]
    @patient.doctor_ids = params[:doctor_ids]
    if params[:new_doctor] != ""
      @patient.doctors << Doctor.create(name: params[:new_doctor])
    end
    @patient.save
    redirect_to patient_path(@patient.id)
  end

  def delete
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path
  end

  def new_prescription
  end

  def create_prescription
  end

  def edit_prescription
  end

  def update_prescription
  end

  def delete_prescription
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>
<%= form_tag doctor_path(@doctor), method: "put" do %>
  <label>Doctor Name:</label><br>
  <%= text_field_tag :'doctor[name]', @doctor.name %><br>

  <label>Specialty:</label><br>
  <%= text_field_tag :'doctor[specialty]', @doctor.specialty %><br>

  <label>Select patients:</label><br>
  <% @patients.each do |patient| %>
    <%= check_box_tag :'patient_ids[]', value="#{patient.id}", checked = @doctor.patient_ids.include?(patient.id) %>
    <%= label_tag :'patient_ids[]', patient.name %>
  <% end %><br>

  <label>Create patient:</label><br>
  <%= text_field_tag :'new_patient' %><br>

  <%= submit_tag "Edit Doctor" %>
<% end %>

app/views/doctors/index.html.erb
<h1> Doctors </h1>
<% @doctors.each do |doctor| %>
<div><%= link_to doctor.format, doctor_path(doctor.id) %></div>
<% end %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>
<%= form_tag doctors_path do %>
  <label>Doctor Name:</label><br>
  <%= text_field_tag :'doctor[name]' %><br>

  <label>Specialty:</label><br>
  <%= text_field_tag :'doctor[specialty]' %><br>

  <label>Select patients:</label><br>
  <% @patients.each do |patient| %>
    <%= check_box_tag :'patient_ids[]', value="#{patient.id}", checked = false %>
    <%= label_tag :'patient_ids[]', patient.name %>
  <% end %><br>

  <label>Create patient:</label><br>
  <%= text_field_tag :'new_patient' %><br>

  <%= submit_tag "Create Doctor" %>
<% end %>

app/views/doctors/show.html.erb
<h1><%=@doctor.name%></h1>
<h2><%=@doctor.specialty%></h1>
<br>
<h3>Currently seeing <%= @doctor.patients.count %> Patients:</h3>
    <%@doctor.patients.each do |patient| %>
      <div><%= link_to patient.name, patient_path(patient.id) %></div>
    <% end %>

<br>
<%= link_to "Edit Doctor", edit_doctor_path(@doctor.id) %>
<%= link_to "Add Patient", patients_new_path %>
<%= link_to "Delete Doctor", delete_doctor_path(@doctor.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrescriptionManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>
<%= form_tag patient_path(@patient), method: "put" do %>
  <label>Patient Name:</label><br>
  <%= text_field_tag :'patient[name]', @patient.name %><br>

  <label>Select doctors:</label><br>
  <% @doctors.each do |doctor| %>
    <%= check_box_tag :'doctor_ids[]', value="#{doctor.id}", checked = @patient.doctor_ids.include?(doctor.id) %>
    <%= label_tag :'doctor_ids[]', doctor.name %>
  <% end %><br>

  <label>Create doctor:</label><br>
  <%= text_field_tag :'new_doctor' %><br>

  <%= submit_tag "Edit Patient" %>
<% end %>

app/views/patients/index.html.erb
<h1> Patient </h1>
<% @patients.each do |patient| %>
<div><%= link_to patient.name, patient_path(patient.id) %></div>
<% end %>

app/views/patients/new.html.erb
<h1>New Patient</h1>
<%= form_tag patients_path do %>
<label>Patient Name:</label><br>
<%= text_field_tag :'patient[name]' %><br>

<label>Select doctors:</label><br>
<% @doctors.each do |doctor| %>
  <%= check_box_tag :'doctor_ids[]', value="#{doctor.id}", checked = false %>
  <%= label_tag :'doctor_ids[]', doctor.name %>
<% end %><br>

<label>Create doctor:</label><br>
<%= text_field_tag :'new_doctor' %><br>

  <%= submit_tag "Create Patient" %>
<% end %>

app/views/patients/new_prescription.html.erb
<h1>New Prescription</h1>
<%= form_tag patient_path(@patient) do %>
<label>Patient Name:</label><br>
<%= text_field_tag :'patient[name]', @patient.name %><br>

<label>Select doctors:</label><br>
<% @doctors.each do |doctor| %>
  <%= check_box_tag :'doctor_ids[]', value="#{doctor.id}", checked = @patient.doctor_ids.include?(doctor.id) %>
  <%= label_tag :'doctor_ids[]', doctor.name %>
<% end %><br>

<label>Create doctor:</label><br>
<%= text_field_tag :'new_doctor' %><br>

  <%= submit_tag "Create Prescription" %>
<% end %>

app/views/patients/show.html.erb
<h1><%=@patient.name%></h1>
<h2>Currently seeing <%= @patient.doctors.count %> Doctors:</h2>
    <%@patient.doctors.each do |doctor| %>
      <div><%= link_to doctor.name, doctor_path(doctor.id) %></div>
    <% end %>

<br>

<h2>Meds:</h2>
<h3>To take in the morning: </h3>
    <%@patient.prescriptions.select {|p| p.t_o_d == "Morning"}.each do |prescription| %>
      <div><%=prescription.format %> - Prescribed by <%=link_to presciription.doctor.name, patient_path(presciription.doctor.id)%></div>
    <% end %>
<h3>To take at midday: </h3>
  <%@patient.prescriptions.select {|p| p.t_o_d == "Midday"}.each do |prescription| %>
    <div><%=prescription.format %> - Prescribed by <%=link_to presciription.doctor.name, patient_path(presciription.doctor.id)%></div>
  <% end %>
<h3>To take in the evening: </h3>
    <%@patient.prescriptions.select {|p| p.t_o_d == "Evening"}.each do |prescription| %>
      <div><%=prescription.format %> - Prescribed by <%=link_to presciription.doctor.name, patient_path(presciription.doctor.id)%></div>
    <% end %>
<br>
<%= link_to "Edit Patient", edit_doctor_path(@patient.id) %>
<%= link_to "Add Doctor", patients_new_path %>
<%= link_to "Delete Patient", delete_patient_path(@patient.id) %>